name: 'Close Issue on PR Merge'
description: 'Closes linked issues when a pull request is merged'
inputs:
  github-token:
    description: >
      Personal access token (PAT) used to fetch the repository. The PAT is
      configured with the local git config, which enables your scripts to run
      authenticated git commands. The post-job step removes the PAT.

      We recommend using a service account with the least permissions necessary.
      Also when generating a new PAT, select the least scopes necessary.

      [Learn more about creating and using encrypted
      secrets](https://help.github.com/en/actions/automating-your-workflow-with-github-actions/creating-and-using-encrypted-secrets)
    required: false
    default: ${{ github.token }}
runs:
  using: 'composite'
  steps:
    - run: ./entrypoint.sh
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PR_BODY: ${{ github.event.pull_request.body }}
        REPO: ${{ github.repository }}
