name: Auto Assign on Issue Comment

on:
  issue_comment:
    types: [ created ]
  issues:
    types: [ opened ]

permissions:
  issues: write

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check comment and assign user
        uses: ./.github/actions/auto-assign

      - name: Inform how to use the bot when a new issue is created
        if: github.event.action == 'opened'
        uses: ./.github/actions/inform-bot