name: Close Issue on PR Merge

on:
  pull_request:
    types: [ closed ]

permissions:
  issues: write
  pull-requests: read

jobs:
  close-issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true


    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Close linked issue
        uses: ./.github/actions/close-issue-on-pr-merge
